export const REGISTER_GUIDE_INPUT_IDs = [
  "certificate",
  "taxId",
  "brandBankAccount",
  "numberBankAccount",
  "nameBankAccount",
];

export const NAME_BRAND_BANK_ACCOUNT = [
  ["Bank for Agriculture and Agricultural Cooperatives", "baac"],
  ["Bank of Ayudhya (Krungsri)", "bay"],
  ["Bangkok Bank", "bbl"],
  ["BNP Paribas", "bnp"],
  ["Bank of America", "boa"],
  ["Crédit Agricole", "cacib"],
  ["CIMB Thai Bank", "cimb"],
  ["Citibank", "citi"],
  ["Deutsche Bank", "db"],
  ["Government Housing Bank", "ghb"],
  ["Government Savings Bank", "gsb"],
  ["Hongkong and Shanghai Banking Corporation", "hsbc"],
  ["Islamic Bank of Thailand", "ibank"],
  ["Industrial and Commercial Bank of China (Thai)", "icbc"],
  ["J.P. Morgan", "jpm"],
  ["Kasikornbank", "kbank"],
  ["Kiatnakin Bank", "kk"],
  ["Krungthai Bank", "ktb"],
  ["Land and Houses Bank", "lhb"],
  ["Mizuho Bank", "mb"],
  ["Mega International Commercial Bank", "mega"],
  ["Bank of Tokyo-Mitsubishi UFJ", "mufg"],
  ["Royal Bank of Scotland", "rbs"],
  ["Standard Chartered (Thai)", "sc"],
  ["Siam Commercial Bank", "scb"],
  ["Sumitomo Mitsui Banking Corporation", "smbc"],
  ["Thai Credit Retail Bank", "tcrb"],
  ["Tisco Bank", "tisco"],
  ["TMBThanachart Bank", "ttb"],
  ["United Overseas Bank (Thai)", "uob"],
];
