name: Test Frontend

on:
  pull_request:
    branches:
      - main
      - beta
      - dev
    paths:
      - "apps/frontend/**"
  workflow_dispatch:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No Unit Test!"'
