name: Test Build Frontend Docker Image

on:
  pull_request:
    branches:
      - main
      - beta
      - dev
    paths:
      - "apps/frontend/**"
  workflow_dispatch:

jobs:
  test_build_image:
    name: Test Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Test Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.frontend
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
