name: Ignore Unit Test

on:
  pull_request:
    branches:
      - main
      - beta
      - dev
    paths-ignore:
      - "apps/frontend/**"
      - "apps/backend/**"
      - "packages/config/**"
      - "packages/database/**"
      - "packages/media-storage/**"
      - "packages/types/**"
  workflow_dispatch:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No Test Required"'
