name: Unit Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: pnpm install
        run: pnpm install --frozen-lockfile
      - name: tests
        working-directory: ./apps/backend
        run: pnpm run test
